server {
    listen 80;
    listen [::]:80;
    server_name cdn.somdomato.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/somdomato.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/somdomato.com/privkey.pem;

    server_name cdn.somdomato.com;
    root /var/www/cdn.somdomato.com;

    include conf.d/sdm-errors.conf;
    include conf.d/cache.conf;
    include conf.d/deny.conf;
}
