export * from '@/routes/main.routes'
export * from '@/routes/radio.routes'
export * from '@/routes/songs.routes'
export * from '@/routes/requests.routes'
export * from '@/routes/history.routes'
export * from '@/routes/upload.routes'