geoip2 /usr/share/GeoIP/GeoLite2-City.mmdb {
    auto_reload 1h;

    $geoip2_country_code default=XX country iso_code;
    $geoip2_country_name default=Unknown country names en;

    $geoip2_region_code default=XX subdivisions 0 iso_code;
    $geoip2_region_name default=Unknown subdivisions 0 names en;

    $geoip2_city_name default=Unknown city names en;
    $geoip2_postal_code default=Unknown postal code;

    $geoip2_latitude default=0 location latitude;
    $geoip2_longitude default=0 location longitude;
    $geoip2_timezone default=Unknown location time_zone;
}